name: Trigger container build in blog repo

on:
  push:
    branches:
      - master

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger workflow in another repository
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.WORKFLOW_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/sarems/blog/actions/workflows/main.yml/dispatches \
          -d '{"ref":"master"}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
